// vite-ts-threlte8/src/App.svelte
<script lang="ts">
  import { Canvas, T } from '@threlte/core'
  import { OrbitControls } from '@threlte/extras'
  import { color } from 'three/tsl'
  import { WebGPURenderer, MeshBasicNodeMaterial } from 'three/webgpu'
  import BackendLogger from './BackendLogger.svelte'
</script>

<main>
  <Canvas createRenderer={canvas => new WebGPURenderer({ canvas })}>
    <T.PerspectiveCamera makeDefault position={[0, 0, 10]}>
      <OrbitControls />
    </T.PerspectiveCamera>

    <T.Mesh>
      <T.BoxGeometry />
      <T is={MeshBasicNodeMaterial} colorNode={color('#fff000')} />
    </T.Mesh>

    <BackendLogger />
  </Canvas>
</main>

<style>
  :global(html, body) {
    margin: 0;
    padding: 0;
  }

  main {
    width: 100vw;
    height: 100vh;
  }
</style>

// vite/src/App.tsx
import { Canvas } from '@react-three/fiber/webgpu'
import { OrbitControls } from '@react-three/drei/core'

const IndexPage = () => (
  <Canvas style={{ height: '100vh' }}>
    <OrbitControls />
    <mesh>
      <boxGeometry />
      <meshBasicMaterial color="red" />
    </mesh>
  </Canvas>
)

export default IndexPage
